version: "1.0"
info:
  model: int-scaffold
packages:
- name: DefaultProject
  gitServerName: myGit
  gitUrl: https://github.com/cgodartSlagsoa
  gitUsername: cgodartSlagsoa
  gitBranch: main
- name: DefaultProject
  version: "1.0"
  gitServerName: myGit
  gitUrl: https://github.com/cgodartSlagsoa
  gitUsername: cgodartSlagsoa
  gitBranch: main
